# Generated by Django 4.0.4 on 2022-06-05 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0004_alter_actor_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Movie Name')),
                ('watch_count', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(upload_to='movie')),
                ('actors', models.ManyToManyField(to='actor.actor')),
            ],
        ),
    ]
