# Generated by Django 4.0.4 on 2022-06-05 03:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='todo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Todo priority'),
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_date',
            field=models.DateField(default='2000-01-01', verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='todo',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Todo name'),
        ),
    ]
