# Generated by Django 4.0.4 on 2022-06-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_tasks_todo_todo_creation_time_todo_is_done_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ('-id',), 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
    ]
