# Generated by Django 4.0.4 on 2022-06-05 16:57

from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_alter_actor_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='gender',
            field=models.CharField(choices=[('F', 'female'), ('M', 'male')], default=re.RegexFlag['MULTILINE'], max_length=1),
        ),
    ]
